### ISSUE TITLE
Missing Files ?

### ISSUE THREAD

**Issue by jedistev** [naviapps/MWSProductsPHPClientLibrary#1]
AS reading your description as I notice there is some change or remove files as no longer need?

> In the /Samples folder you will find files that correspond to a particular Amazon Marketplace Web Service (Amazon MWS) operation. These files serve as examples to illustrate the code required to make the call for that particular operation. We will be using the SubmitFeed operation from the Feeds API section as an example.
>  
> Open /Samples/SubmitFeedSample.php

There are no SubmitFeedSample.php in the folder.

**Comment by naviapis** [comment]
Updated from Library Version 2016-06-01 to Library Version 2017-03-22.

The library of MWS is divided into multiple parts, and this is Products API Section Client Library.
https://developer.amazonservices.com/doc/products/products/v20111001/php.html/133-8165104-5987453

The Feed API including `SubmitFeedSample.php` is here.
https://developer.amazonservices.com/doc/bde/feeds/v20090101/php.html/133-8165104-5987453

If necessary it will be managed so please tell me.

**Comment by naviapis** [comment]
This `README.md` is included in the original library.
Because the content is not appropriate such as `/Samples/SubmitFeedSample.php` not included in the library, please refer to the reference level.
